name: BubbleChat

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  readme:
    runs-on: ubuntu-latest

    steps:
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: junny
          author_email: chbe5082@naver.com
          message: "Auto updating my readme"
          add: "*.svg"
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
